# sonar-project.properties
# Configuración del análisis estático con SonarCloud

sonar.projectKey=Crisso29_Lab08
sonar.projectName=Lab08 - Pipeline CI/CD
sonar.organization=crisso29

# Solo el código fuente — NO incluir los tests aquí
sonar.sources=src

# Carpeta de tests separada
sonar.tests=UnitTest

# Exclusiones
sonar.exclusions=**/node_modules/**,**/coverage/**

# Reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8