# sonar-project.properties
# Configuración del análisis estático con SonarCloud

# Identificador único del proyecto en SonarCloud
sonar.projectKey=Crisso29_Lab08

# Nombre que aparece en el dashboard de SonarCloud
sonar.projectName=Lab08 - Pipeline CI/CD

# Organización en SonarCloud (tu usuario de GitHub en minúsculas)
sonar.organization=crisso29

# Carpetas a analizar (código fuente y tests)
sonar.sources=src,UnitTest,E2ETest
sonar.exclusions=**/node_modules/**,**/coverage/**

# Carpeta de tests unitarios
sonar.tests=UnitTest

# Reporte de cobertura generado por Jest
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Versión del código
sonar.projectVersion=1.0

# Encoding
sonar.sourceEncoding=UTF-8